/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class NewJFrame extends javax.swing.JFrame {

	private static final long serialVersionUID = 1L;
	private JButton g1;
	private JButton g2;
	private JButton g3;
	private JButton g4;
	private JButton g5;
	private JButton g6;
	private JButton g7;
	private JButton g8;
	private JButton g9;

	/**
	 * Creates new form NewJFrame
	 * 
	 * @throws IOException
	 */
	public NewJFrame() throws IOException {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 * 
	 * @throws IOException
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() throws IOException {

		jPanel1 = new JPanel();
		jButton1 = new JButton();
		jButton2 = new JButton();
		jButton3 = new JButton();
		jButton4 = new JButton();
		jButton5 = new JButton();
		jPanel2 = new JPanel();
		jButton6 = new JButton();
		jButton7 = new JButton();
		jButton8 = new JButton();
		jButton9 = new JButton();
		jButton10 = new JButton();
		jPanel4 = new JPanel();
		jPanel5 = new JPanel();
		jButton12 = new JButton();
		jButton13 = new JButton();
		jButton14 = new JButton();

		setDefaultCloseOperation(EXIT_ON_CLOSE);

		jPanel1.setBackground(new Color(204, 255, 255));
		jPanel1.setMaximumSize(new Dimension(100, 32767));

		jButton1.setBackground(new Color(204, 255, 255));
		jButton1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
		jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/store.png"))); // NOI18N
		jButton1.setText("Tại bàn");
		jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jButton1.setMaximumSize(new java.awt.Dimension(10, 10));
		jButton1.addActionListener(new ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setBackground(new java.awt.Color(204, 255, 255));
		jButton2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bill.png"))); // NOI18N
		jButton2.setText("Tại Quầy");
		jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

		jButton3.setBackground(new java.awt.Color(204, 255, 255));
		jButton3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
		jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/customer.png"))); // NOI18N
		jButton3.setText("Khách Hàng");
		jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

		jButton4.setBackground(new java.awt.Color(204, 255, 255));
		jButton4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
		jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report.png"))); // NOI18N
		jButton4.setText("Thống Kê");
		jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

		jButton5.setBackground(new java.awt.Color(204, 255, 255));
		jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
		jButton5.setText("Trang chủ");
		jButton5.setToolTipText("");
		jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
				.addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
				.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
				.addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(16, 16, 16)
						.addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
						.addGap(0, 0, 0)
						.addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
						.addGap(0, 0, 0)
						.addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
						.addGap(0, 0, 0)
						.addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
						.addGap(0, 0, 0)
						.addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
						.addGap(0, 217, Short.MAX_VALUE)));

		jPanel2.setBackground(new java.awt.Color(204, 255, 255));

		jButton6.setText("Nước có ga");

		jButton7.setText("Nước suối");

		jButton8.setText("Nước ép trái cây");

		jButton9.setText("Nước ép rau củ");

		jButton10.setText("Cà phê");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		// Tạo JPanel mới
		JPanel panelTaiQuay = new JPanel();

		// Thêm JPanel vào jPanel2Layout
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 170,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 170,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 170,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 170,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButton10,
								javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addComponent(panelTaiQuay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));

		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup()
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(panelTaiQuay,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
// thêm sản phẩm vào panel
		panelTaiQuay.setLayout(new GridLayout(3, 3));
		// sp1
		g1 = new JButton();
		g1.setMargin(new Insets(0, 0, 0, 0));
		g1.setBackground(new Color(41, 255, 255));
		BufferedImage origin1 = ImageIO.read(new File("img//coca-cola.jpg"));
		Image sclaleImg1 = origin1.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
		ImageIcon icon1 = new ImageIcon(sclaleImg1);
		g1.setIcon(icon1);
		g1.setName("SP001");
		panelTaiQuay.add(g1);
		// sp2
		g2 = new JButton();
		g2.setMargin(new Insets(0, 0, 0, 0));
		g2.setBackground(new Color(41, 255, 255));
		BufferedImage origin2 = ImageIO.read(new File("img//pepsi.jpg"));
		Image sclaleImg2 = origin2.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
		ImageIcon icon2 = new ImageIcon(sclaleImg2);
		g2.setIcon(icon2);
		g2.setName("SP002");
		panelTaiQuay.add(g2);

		// sp3
		g3 = new JButton();
		g3.setMargin(new Insets(0, 0, 0, 0));
		g3.setBackground(new Color(41, 255, 255));
		BufferedImage origin3 = ImageIO.read(new File("img//7-up.jpg"));
		Image sclaleImg3 = origin3.getScaledInstance(200, 150, Image.SCALE_SMOOTH);
		ImageIcon icon3 = new ImageIcon(sclaleImg3);
		g3.setIcon(icon3);
		g3.setName("SP003");
		panelTaiQuay.add(g3);

		// sp4
		g4 = new JButton();
		g4.setMargin(new Insets(0, 0, 0, 0));
		g4.setBackground(new Color(41, 255, 255));
		BufferedImage origin4 = ImageIO.read(new File("img//mountain-new.jpg"));
		Image sclaleImg4 = origin4.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
		ImageIcon icon4 = new ImageIcon(sclaleImg4);
		g4.setIcon(icon4);
		g4.setName("SP004");
		panelTaiQuay.add(g4);

		// sp5
		g5 = new JButton();
		g5.setMargin(new Insets(0, 0, 0, 0));
		g5.setBackground(new Color(41, 255, 255));
		BufferedImage origin5 = ImageIO.read(new File("img/sting-yellow.jpg"));
		Image sclaleImg5 = origin5.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
		ImageIcon icon5 = new ImageIcon(sclaleImg5);
		g5.setIcon(icon5);
		g5.setName("SP005");
		panelTaiQuay.add(g5);

		// sp6
		g6 = new JButton();
		g6.setMargin(new Insets(0, 0, 0, 0));
		g6.setBackground(new Color(41, 255, 255));
		BufferedImage origin6 = ImageIO.read(new File("img//sting-yellow.jpg"));
		Image sclaleImg6 = origin6.getScaledInstance(200, 150, Image.SCALE_SMOOTH);
		ImageIcon icon6 = new ImageIcon(sclaleImg6);
		g6.setIcon(icon6);
		g6.setName("SP006");
		panelTaiQuay.add(g6);

		// sp7
		g7 = new JButton();
		g7.setMargin(new Insets(0, 0, 0, 0));
		g7.setBackground(new Color(41, 255, 255));
		BufferedImage origin7 = ImageIO.read(new File("img//sting-green.jpg"));
		Image sclaleImg7 = origin7.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
		ImageIcon icon7 = new ImageIcon(sclaleImg7);
		g7.setIcon(icon7);
		g7.setName("SP007");
		panelTaiQuay.add(g7);

		// sp8
		g8 = new JButton();
		g8.setMargin(new Insets(0, 0, 0, 0));
		g8.setBackground(new Color(41, 255, 255));
		BufferedImage origin8 = ImageIO.read(new File("img//sprite.jpg"));
		Image sclaleImg8 = origin8.getScaledInstance(200, 200, Image.SCALE_SMOOTH);
		ImageIcon icon8 = new ImageIcon(sclaleImg8);
		g8.setIcon(icon8);
		g8.setName("SP008");
		panelTaiQuay.add(g8);

		// sp9
		g9 = new JButton();
		g9.setMargin(new Insets(0, 0, 0, 0));
		g9.setBackground(new Color(41, 255, 255));
		BufferedImage origin9 = ImageIO.read(new File("img//red-bull.jpg"));
		Image sclaleImg9 = origin9.getScaledInstance(200, 150, Image.SCALE_SMOOTH);
		ImageIcon icon9 = new ImageIcon(sclaleImg9);
		g9.setIcon(icon9);
		g9.setName("SP009");
		panelTaiQuay.add(g9);
		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 30, Short.MAX_VALUE));

		jButton12.setText("jButton11");

		jButton13.setText("jButton11");

		jButton14.setText("jButton11");

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout
				.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel5Layout.createSequentialGroup().addGap(87, 87, 87).addComponent(jButton12)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jButton13)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButton14)));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jButton12).addComponent(jButton13).addComponent(jButton14))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jPanel5,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE))
				.addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton5ActionPerformed

	private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton10ActionPerformed

	}// GEN-LAST:event_jButton10ActionPerformed

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton9ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton9ActionPerformed

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton8ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton8ActionPerformed

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton7ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton7ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					new NewJFrame().setVisible(true);
				} catch (IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton14;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	// End of variables declaration//GEN-END:variables

}